### ISSUE TITLE
有关Causal Mask的分析实验

### ISSUE THREAD

**Issue by ZMingHang** [PositionalHidden/PositionalHidden#4]
如果想要实现论文section 2.2中Causal Mask的分析实验，应该如何运行代码

**Comment by yuyijiong** [comment]
分析实验的代码没有在这个repo里。如果想要改causal mask，需要修改LlamaAttention, 将 attention mask 替换为人工修改过的mask。

**Comment by ZMingHang** [comment]
好的，感谢！
