### ISSUE TITLE
如何确定最终的factor与layers

### ISSUE THREAD

**Issue by ALONGNEU** [PositionalHidden/PositionalHidden#5]
请问如何根据step1中的结果确定后续evaluation时候的factor与layers呢？
看到论文里paper关于factor的结论是0.5~-1之间，那么该选择最佳值呢？
![image](https://github.com/user-attachments/assets/e0bf398d-e744-41c4-9fd2-3af1387c71b4)

thx

**Comment by yuyijiong** [comment]
这个一般是基于经验判断的，只能多试几次。
根据经验来说，通常选取layer=10~(total_layers-6) 会比较好，选取全部layer不太好。
一般的模型factor取0比较好，但对于llama2取-1提升会更大，因为不同模型的bias程度不同。

**Comment by ALONGNEU** [comment]
那大体流程就是通过step1来筛选出dim，factor与layers的具体设置只能通过经验来判断了，这么理解对嘛？

**Comment by yuyijiong** [comment]
factor可以通过验证集上的loss选出比较好的值。
layers是基于经验的。

**Comment by ALONGNEU** [comment]
好的，多谢！
